### ISSUE TITLE
Lag en "for (let)" loop som går igjennom dataen og å kunne tegne sirkler og streker

### ISSUE THREAD

**Issue by jonaslefdal** [jonaslefdal/HOW-WE-ROLL-8B#13]
Denne må kunne gå igjennom all daten og plassere alle flere sirkler på flere linjer. Hver linje inneholder sirkler tilhørende sitt eget spørsmål.

**Comment by jonaslefdal** [comment]
@mathhaug Kan du se om du kan lage noe som fungere her? Bare rediger på Ny_output filen. Du trenger sikkert en ny for let loop som kan gå over propertiesene innenfor hvert element elns?

**Comment by mathhaug** [comment]
Ja burde vell sikkert ha en funskjon som øker y verdien etter hver gjennomgang også. Skal se på det nå
